version: '3'

services:
  db:
    container_name: nestPg
    build:
      context: ./
      dockerfile: dockerfile.pg
    volumes:
      - ./dbVolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    tty: true