version: '3'

services:
  db:
    container_name: nestPg
    build:
      context: src/database
      dockerfile: pg.dockerfile
    volumes:
      - ./dbVolume:/var/lib/postgresql/data
    ports:
      - 5432:5432